config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes do
  	resources :steps, only: [:new, :create, :edit, :update]
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord


end

# https://gist.github.com/arjunvenkat/1115bc41bf395a162084

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	has_many :steps
	accepts_nested_attributes_for :steps,allow_destroy: true,
 						reject_if: proc { |attributes| attributes['step'].blank? }

end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :recipe, optional: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes=Recipe.all
	end

	def new
		@recipe=Recipe.new
	end

	def create
		@recipe=Recipe.create( recipe_params )
		if @recipe.save 
			redirect_to new_recipe_step_path(@recipe)
		else 
			render :action => :new
		end
	end

	def edit
		@recipe=Recipe.find(params[:id])
	end

	def update
		@recipe=Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			flash[:notice]="Post was successfully updated"
			redirect_to edit_recipe_path(@recipe)
		else 
			flash[:notice]="Post was not saved. Please retry."
			render :action => :new	
		end
	end

	def show
		@recipe=Recipe.find(params[:id])
	end

	def destroy
		@recipe=Recipe.find(params[:id])
		@recipe.destroy
		redirect_to recipes_path
	end

	private

	def recipe_params
		params.require(:recipe).permit(:avatar,:name,:description,:preptime,steps_attributes: [:number, :description])
	end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

	before_action :set_recipe

	def index
	end
	
	def new
		@step=@recipe.steps.new
	end

	def create
		@step=@recipe.steps.create( steps_params )
		@step.save 
		# 	flash[:notice]="Recipe has been saved."
		# 	redirect_to recipe_path(@recipe)
		# else 
		# 	flash[:notice]="Recipe was not saved. Please retry."
		# 	render :action => :new
		# end
	end

	def edit 
	end

	def update
	end

	protected 

	def set_recipe
	 	@recipe = Recipe.find(params[:recipe_id])
	end

	def steps_params
		params.require(:step).permit(:number,:description,:recipe_id, )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honestbee</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>

    <%= yield %>
  </body>
</html>

app/views/recipes/_step_fields.html.erb
<div class='nested-fields'>
    <%= f.input :step %>
    <%= link_to_remove_association "remove step", f %>
</div>

app/views/recipes/edit.html.erb
<%= form_for @recipe, :url => recipe_path(@recipe), html: { multipart: true } do |f| %>

  <div>
  Name:
  <%= f.text_field :name %>
  </div>

  <div>
  Description:
  <%= f.text_field :description %>
  </div>

  <div>
  Preparation Time (in mins)
  <%= f.text_field :preptime %>
  </div>

  <div>
  <%= f.file_field :avatar %>
  </div>

  <div>
  <%= f.submit %>
  </div>
  
<% end %>

app/views/recipes/index.html.erb
<div class="page-header">
	<div class="row">
		<div class="container col-xs-4">
		</div>
		<div class="container col-xs-4">
			<%= image_tag "RECIBEE-02.jpg", class: "img-responsive"%>
		</div>
	</div>
	<div>
		<div class="container col-xs-5">
		</div>
		<div>
			<%= link_to 'Create new recipe', new_recipe_path, class: "btn btn-primary" %>
		</div>
	</div>
</div>

<div class="container recipe">
	<div class="row">
		<div class="container col-xs-3">
			<% @recipes.each do |p| %>
				<h4><%= p.name %></p></h4>
				<p><%= p.description %></p>
				<p>Preparation Time (mins): <%= p.preptime %></p>
				<%= image_tag p.avatar.url, class: "img-responsive" %>
				<%= link_to "Show", recipe_path(p) %>
				<%= link_to "Edit", edit_recipe_path(p) %>
				<%= link_to "Delete", recipe_path(p),:method=>:delete %>
			<% end %>
		</div>
	</div>
</div>

<div class="container">
<h1></h1>
</div>

app/views/recipes/new.html.erb
<%= form_for @recipe, :url => recipes_path, html: { multipart: true } do |f| %>

  <div>
  Name:
  <%= f.text_field :name %>
  </div>

  <div>
  Description:
  <%= f.text_field :description %>
  </div>

  <div>
  Preparation Time (in mins)
  <%= f.text_field :preptime %>
  </div>

  <div>
  <%= f.file_field :avatar %>
  </div>

  <div>
  <%= f.submit %>
  </div>
  
<% end %>

app/views/recipes/show.html.erb
<div class="container recipe">
	<div class="row">
		<div class="container col-xs-3">
			<h4><%= @recipe.name %></p></h4>
			<p><%= @recipe.description %></p>
			<p>Preparation Time (mins): <%= @recipe.preptime %></p>
			<%= image_tag @recipe.avatar.url, class: "img-responsive" %>
			<p> Instructions: </p>
			<%= link_to "Main Page", recipe_path %>
		</div>
	</div>
</div>

app/views/steps/_step_fields.html.erb
<div class='nested-fields'>
    <%= f.input :description %>
    <%= link_to_remove_association "remove step", f %>
</div>

app/views/steps/new.html.erb
<%= simple_form_for @recipe, :url => recipe_path(@recipe), :method => :patch, html: { multipart: true } do |f| %>
  <div>
    <%= f.simple_fields_for :steps do |step| %>
      <%= render 'step_fields', :f => step %>
    <% end %>
  <div>
      <%= link_to_add_association 'add step', f, :steps %>
   </div>
 </div>
    <%= f.submit 'Save' %>
<% end %>